[tool.isort]
profile = "black"
line_length = 119

[tool.black]
line-length = 119
target-version = ['py310']
required-version = "23"
skip-string-normalization = true

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
pretty = true
no_implicit_optional = true
install_types = true
non_interactive = true # install types silently
show_error_codes = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
check_untyped_defs = true
